### ISSUE TITLE
group types nodes are containing types but don't specify dimensions

### ISSUE THREAD

**Issue by pketh** [obsidianmd/jsoncanvas#16]
I'm not sure if `group` nodes are supposed to act like `boxes` in Kinopio which are a type of node that can contain other nodes. If so, to draw a box I would need a `width` and `height` (and ideally a color) to know how to draw it. These attributes aren't specified in the docs though.

![image](https://github.com/obsidianmd/jsoncanvas/assets/877072/9c4a98a9-770b-4f1e-9bbc-2a11fe7db23e)

**Comment by jjspace** [comment]
The spec is a little hard to understand because the information is spread apart but the properties under `Generic node` apply to all nodes. I misread this the first time through too

> All node include the following attributes:

The properties under each node type are _in addition_ to those base properties so group nodes do have a width and height. The spec could probably make this a little clearer, maybe a line under each type that says "in addition to the generic properties" or something

A group might look like this: 

```json
{
  {
    "id":"f87185488832096d",
    "type":"group",
    "x":-680,
    "y":1156,
    "width":546,
    "height":734,
    "label":"Group"
  }
}
```
(pulled from one of my Obsidian files which is probably the most accurate example implementation we have so far)

**Comment by kepano** [comment]
As @jjspace stated, groups can contain width/height and other properties that belong to a generic node, we'll make that clearer in the docs.

**Comment by pketh** [comment]
as a bonus, having a basic `group` in the example spec canvas file would help a lot too and give me something I can confidently test against

**Comment by kepano** [comment]
Done
